# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
#Use when service is running on docker and agent is running locally on Mac/Windows
#Ensure that agent is configured for container data by setting apm_config and apm_non_local_traffic:true in datadog.yaml file
version: '3'
services:
  producer:
    container_name: producer
    restart: always
    build: 
       context: ../kafka-producer
       dockerfile: ../kafka-producer/dockerfile.producer.maven
    ports:
      - 8080:8080
    labels:
      - com.datadoghq.tags.service="producer"
      - com.datadoghq.tags.env="dev"
      - com.datadoghq.tags.version="0.0.1"
    environment:
      - DD_SERVICE=producer
      - DD_ENV=dev
      - DD_VERSION=0.0.1
      - DD_AGENT_HOST=host.docker.internal