version: "3.7"

services:
#  sql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rootPass
#    ports:
#      - 33060:3306

  cassandra-seed:
    container_name: cassandra-seed
    image: cassandra:3.11
    ports:
      - "9042:9042"
    volumes:
      - local_cassandra_data_seed:/var/lib/cassandra

volumes:
  local_cassandra_data_seed: