server:
  port: 8085

spring:
  application:
    name: kafka-consumer
  kafka:
    topic-name: order_topic
    consumer:
      bootstrap-servers: localhost:9093
      group-id: kafka-training-consumer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: "OrderDto:com.example.orderconsumer.infrastructure.kafka.OrderDto"
        spring.json.value.default.mapping: "com.example.orderconsumer.infrastructure.kafka.OrderDto"
        spring.json.use.type.headers: true

  datasource:
    name: customer-database
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    data:
      repository:
        autotime:
          enabled: true
  datadog:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false

