spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.orderconsumer.infrasructure.OrderDtoDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  consumer-group-id: kafka-training-consumer
  topic-name: "order_topic"
