spring:
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.ordermessage.order.infrastructure.OrderEventSerializer

kafka:
  topic-name: "order_topic"

server:
  port: 8081