spring:
  application:
    name: kafka-producer
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.ordermessage.order.infrastructure.OrderEventSerializer

kafka:
  topic-name: "order_topic"

server:
  port: 8080

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false
management:
  tracing:
    sampling:
      probability: 1.0
  datadog:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false



